### ISSUE TITLE
Add ability to write ArraySegment<> or Memory<> to Pile, reusing the underlying buffer used for temp format transofrmation during serialization

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#135]

**Comment by zhabis** [comment]
Added `Subarray<T>` to Pile

**Comment by erxdkh** [comment]
Error thrown by   memory stream: Capacity was less than the current size

 at System.IO.MemoryStream.set_Capacity(Int32 value)
   at Azos.Serialization.Arow.ArowSerializer.SerializeToSubarray(TypedDoc doc) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Arow\ArowSerializer.cs:line 140
   at Erx.Business.Security.Laker.Data.SecurityDatabase.<workBody>d__33.MoveNext() in C:\edev\erx\Business\src\Erx.Business.Security\Laker\Data\SecurityDatabase.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Erx.Business.Security.Laker.Data.SecurityDatabase.<work>d__32.MoveNext() in C:\edev\erx\Business\src\Erx.Business.Security\Laker\Data\SecurityDatabase.cs:line 162

**Comment by zhabis** [comment]
DONE
