### ISSUE TITLE
MVC handler error in work processing: [Azos.Wave.WaveException] Error reflecting on MVC controller type 'Erx.Business.Api.Controllers.OAuth' action ''. Error: [System.Reflection.AmbiguousMatchException] Multiple custom attributes of the same type found.

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#164]
Error Happened
Request processing generated an error. Please contact the site administrator.
1. Azos.Wave.MvcException
MVC handler error in work processing: [Azos.Wave.WaveException] Error reflecting on MVC controller type 'Erx.Business.Api.Controllers.OAuth' action ''. Error: [System.Reflection.AmbiguousMatchException] Multiple custom attributes of the same type found.
Stack:
at Azos.Wave.Handlers.MvcHandler.DoError(WorkContext work, Exception error) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Handlers\MVCHandler.cs:line 152
at Azos.Wave.Handlers.TypeLookupHandler`1.DoHandleWork(WorkContext work) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Handlers\TypeLookupHandler.cs:line 173
at Azos.Wave.WorkHandler.HandleWork(WorkContext work) in C:\Zdev\ghub\AZOS\src\Azos.Wave\WorkHandler.cs:line 172
at Azos.Wave.WorkFilter.InvokeNextWorker(WorkContext work, IList`1 filters, Int32 thisFilterIndex) in C:\Zdev\ghub\AZOS\src\Azos.Wave\WorkFilter.cs:line 160
at Azos.Wave.Filters.SessionFilter.DoFilterWork(WorkContext work, IList`1 filters, Int32 thisFilterIndex) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Filters\SessionFilter.cs:line 94
at Azos.Wave.WorkFilter.FilterWork(WorkContext work, IList`1 filters, Int32 thisFilterIndex) in C:\Zdev\ghub\AZOS\src\Azos.Wave\WorkFilter.cs:line 122
2. Azos.Wave.WaveException
Error reflecting on MVC controller type 'Erx.Business.Api.Controllers.OAuth' action ''. Error: [System.Reflection.AmbiguousMatchException] Multiple custom attributes of the same type found.
Stack:
at Azos.Wave.Mvc.ControllerInfo..ctor(Type type) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Mvc\Reflection.cs:line 64
at Azos.Wave.Handlers.MvcHandler.FindMatchingAction(Controller controller, WorkContext work, String action, Object[]& args) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Handlers\MVCHandler.cs:line 177
at Azos.Wave.Handlers.MvcHandler.DoTargetWork(Controller target, WorkContext work) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Handlers\MVCHandler.cs:line 64
at Azos.Wave.Handlers.TypeLookupHandler`1.DoHandleWork(WorkContext work) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Handlers\TypeLookupHandler.cs:line 161
3. System.Reflection.AmbiguousMatchException
Multiple custom attributes of the same type found.
Stack:
at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
at Azos.Wave.Mvc.ControllerInfo.GetInvocationName(MethodInfo mi) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Mvc\Reflection.cs:line 30
at Azos.Wave.Mvc.ControllerInfo..ctor(Type type) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Mvc\Reflection.cs:line 49

**Comment by zhabis** [comment]
DONE  43474c5
