### ISSUE TITLE
.see() is crashing with [System.ArgumentNullException] Value cannot be null. format excpetion

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#180]
Parameter name: format
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Azos.Scripting.SeeUtils.See(String text, Object[] args) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\testing\SeeUtils.cs:line 38

**Comment by zhabis** [comment]
DONE
