### ISSUE TITLE
We need ability to prototype-chain Field attributes within the same document based on target name

### ISSUE THREAD

**Issue by itadapter** [azist/azos#218]
This is needed to drastically reduce the number of metadata decorations on complex model as otherwise we would need to repeat very many meta fields on every field per every target.

We have considered different cases including partial per-target validation which is going to over-complicate the design in many areas.

Something like this would clone ALL meta attributes from the source `cloneSchema` into the target one:
```csharp
[Field(Description="Will be inherited")]
[Field(cloneTarget: null, targetName: "special", Required=true)]
public string Field1 {get;set;}
```

**Comment by zhabis** [comment]
The metadata content understands standard override pragmas. The value list content merges keys from parent that are NOT in child (so child takes precedence), then if any keys are marked as "#del#" get removed. Excample:

```csharp
 "a: aplle, b:boy, c:car"
overide
 "d:data,a:adam,b:#del#"
yields 
 " a:adam,c:car,d:data"

```

**Comment by itadapter** [comment]
@zhabis Will the inheritance work with dynamic schemas attributes? for non-typed docs?

**Comment by itadapter** [comment]
The .Core tests fail after these changes 0decc0d , the .Net tests are fine:
![image](https://user-images.githubusercontent.com/2273574/70674790-0e8ad980-1c55-11ea-9790-32017acf0f05.png)

```
Error #1 from: Azos.Tests.Nub.DataAccess.SchemaEQU{Method 'TypedRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.SchemaEQU.TypedRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\SchemaEQU.cs:line 45

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441

  Error #2 from: Azos.Tests.Nub.DataAccess.SchemaEQU{Method 'DynamicRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.SchemaEQU.DynamicRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\SchemaEQU.cs:line 82

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441

  Error #3 from: Azos.Tests.Nub.DataAccess.Serialization{Method 'Slim_SerializeTable_TypedRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.Serialization.Slim_SerializeTable_TypedRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\Serialization.cs:line 46

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441

  Error #4 from: Azos.Tests.Nub.DataAccess.Serialization{Method 'Slim_SerializeTable_DynamicRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.Serialization.Slim_SerializeTable_DynamicRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\Serialization.cs:line 83

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441


   OK: 168   ERROR: 4    TOTAL:  172
```

**Comment by zhabis** [comment]
Preview is in `Nuget 1.0.535`

**Comment by itadapter** [comment]
@foliage71  The documentation for field inheritance/derivation (as needed in NCPDP data documents) was added here:     https://github.com/azist/azos/blob/master/src/Azos/Data/advanced-meta.md

It is also referenced from Azos Documentation Index in the solution root.

**Comment by itadapter** [comment]
The feature undergoes testing in real business case scenarios. Candidate for closing

**Comment by zhabis** [comment]
This is done, apart from serialization issue on Core which is separate #220 now
