### ISSUE TITLE
Serialization error in .Core: Tests fail after these changes 0decc0d , the .Net tests are fine:

### ISSUE THREAD

**Issue by itadapter** [azist/azos#220]
The .Core tests fail after these changes 0decc0d , the .Net tests are fine:
![image](https://user-images.githubusercontent.com/2273574/70674790-0e8ad980-1c55-11ea-9790-32017acf0f05.png)

```
Error #1 from: Azos.Tests.Nub.DataAccess.SchemaEQU{Method 'TypedRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.SchemaEQU.TypedRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\SchemaEQU.cs:line 45

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441

  Error #2 from: Azos.Tests.Nub.DataAccess.SchemaEQU{Method 'DynamicRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.SchemaEQU.DynamicRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\SchemaEQU.cs:line 82

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441

  Error #3 from: Azos.Tests.Nub.DataAccess.Serialization{Method 'Slim_SerializeTable_TypedRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.Serialization.Slim_SerializeTable_TypedRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\Serialization.cs:line 46

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441

  Error #4 from: Azos.Tests.Nub.DataAccess.Serialization{Method 'Slim_SerializeTable_DynamicRows'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.DataAccess.Serialization.Slim_SerializeTable_DynamicRows() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\DataAccess\Serialization.cs:line 83

[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[2]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441


   OK: 168   ERROR: 4    TOTAL:  172
```

_Originally posted by @itadapter in https://github.com/azist/azos/issues/218#issuecomment-564809308_

**Comment by itadapter** [comment]
This is related to activities under #218, after refactoring of `[FieldAttribute]` the .Core tests started to fail, but  they are running just fine on a .Net Fx  runtime

**Comment by zhabis** [comment]
This is still an issue

**Comment by erxdkh** [comment]
Still an issue in unit tests that use Pile cache while running on CORE
```
[Error[1]] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Pile.DefaultPileBase.deserialize(Memory data, Int32 addr, Int32 payloadSize, Byte serVersion) in C:\Zdev\ghub\AZOS\src\Azos\Pile\PileImpl\DefaultPileBase.cs:line 1424
   at Azos.Pile.DefaultPileBase.get(PilePointer ptr, Boolean raw, Byte& serVersion) in C:\Zdev\ghub\AZOS\src\Azos\Pile\PileImpl\DefaultPileBase.cs:line 794
   at Azos.Pile.DefaultPileBase.Get(PilePointer ptr) in C:\Zdev\ghub\AZOS\src\Azos\Pile\PileImpl\DefaultPileBase.cs:line 732
   at Azos.Pile.LocalCacheTable`1.Get(TKey key, Int32 ageSec) in C:\Zdev\ghub\AZOS\src\Azos\Pile\LocalCacheTable.cs:line 713
   at Azos.Data.CacheExtensions.FetchThroughAsync[TKey,TResult](ICache cache, TKey key, String tblCache, ICacheParams caching, Func`2 fFetch, Func`3 fFilter, Action`4 extraPut) in C:\Zdev\ghub\AZOS\src\Azos\Data\CacheExtensions.cs:line 180
   at Erx.Strangle.Laker.Queries.Membership.GetMemberList.DoExecuteParameterizedQuery(OracleCRUDQueryExecutionContext ctx, Query query, MemberListFilter queryParameters) in C:\edev\erx\Architecture\src\strangle\Erx.Strangle.Laker\Queries\Membership\GetMemberList.cs:line 70
   at Erx.Strangle.Laker.LakerQueryHandler`1.ExecuteAsync(OracleCRUDQueryExecutionContext context, Query query, Boolean oneRow) in C:\edev\erx\Architecture\src\strangle\Erx.Strangle.Laker\LakerQueryHandler.TQueryParameters.cs:line 24
   at Erx.Data.ErxQueryHandler`2.ProfileAsync[T](Func`1 body) in C:\edev\erx\Architecture\src\Erx\Data\ErxQueryHandler.cs:line 48
   at Azos.Data.Access.Oracle.OracleCRUDDataStoreBase.DoLoadAsync(OracleConnection cnn, OracleTransaction transaction, Query[] queries, Boolean oneDoc) in C:\Zdev\ghub\AZOS\src\providers\Azos.Oracle\OracleCRUDDataStoreBase.cs:line 219

[Error[2]] [Azos.Serialization.Slim.SlimDeserializationException] Exception leaked from OnDeserializationCallback() invoked by SlimSerializer. Error:  [System.InvalidCastException] Object must implement IConvertible.
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\SlimSerializer.cs:line 445
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\SlimSerializer.cs:line 243

[Error[3]] [System.InvalidCastException] Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.FormatterConverter.Convert(Object value, Type type)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.HashSet`1.OnDeserialization(Object sender)
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\SlimSerializer.cs:line 441
```
