### ISSUE TITLE
Glue: DIV0 error at Glue\Implementation\CallsWithTasks.cs:line 37

### ISSUE THREAD

**Issue by zhabis** [azist/azos#23]
```
[Error] [System.AggregateException] One or more errors occurred. (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.) (Attempted to divide by zero.)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`2 body)
   at Azos.Tests.Unit.Glue.TestLogic.TASK_TestContractB_4_Parallel(String CONF_SRC, Boolean threadSafe) in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Unit\Glue\TestLogic.cs:line 517
   at Azos.Tests.Unit.Glue.MpxTests.Mpx_TASK_B_4_Parallel_ThreadSafeServer() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Unit\Glue\MpxTests.cs:line 198

[Error[1]] [System.DivideByZeroException] Attempted to divide by zero.
   at Azos.Glue.Implementation.CallsWithTasks.Put(CallSlot call) in C:\Zdev\ghub\azos\src\Azos\Glue\Implementation\CallsWithTasks.cs:line 37
   at Azos.Glue.Implementation.GlueDaemon.SubscribeCallSlotWithTaskReactor(CallSlot call) in C:\Zdev\ghub\azos\src\Azos\Glue\Implementation\GlueDaemon.cs:line 318
   at Azos.Glue.CallSlot.get_AsTask() in C:\Zdev\ghub\azos\src\Azos\Glue\CallSlot.cs:line 246
   at Azos.Tests.Unit.Glue.TestLogic.<>c__DisplayClass19_0.<TASK_TestContractB_4_Parallel>b__0(Int32 i, ParallelLoopState loop) in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Unit\Glue\TestLogic.cs:line 526
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by zhabis** [comment]
While running unit tests

**Comment by zhabis** [comment]
DONE
