### ISSUE TITLE
Exception in Log Message constructor thrown on process terminate

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#233]
```
Web server started on http://+:8099/
Use browser, Insomnia or any REST client to test, for example http://+:8099/doc/toc
Strike <ENTER> to stop the process...



Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Azos.Log.Message..ctor()
   at Azos.Wave.WorkContext.Log(MessageType type, String text, String from, Exception error, String pars, Nullable`1 related)
   at Azos.Wave.Response.Destructor()
   at Azos.DisposableObject.Finalize()

c:\edev\erx\Business\out\Debug>
c:\edev\erx\Business\out\Debug>
```

**Comment by zhabis** [comment]
Can not reproduce

**Comment by erxdkh** [comment]
Here ya go again, this happens when process gets stopped WHILE db call (ORACLE in our case) is hanging due to DB not responding:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Azos.Log.Message..ctor()
   at Azos.Wave.WorkContext.Log(MessageType type, String text, String from, Exception error, String pars, Nullable`1 related)
   at Azos.Wave.Response.Destructor()
   at Azos.DisposableObject.Finalize()

**Comment by erxdkh** [comment]
This is a 100% reproducible bug. Just terminate the web host process while having DB call hanging waiting for Oracle return
