### ISSUE TITLE
Strange cache issue

### ISSUE THREAD

**Issue by foliage71** [azist/azos#283]
Error #1 from: Erx.Business.Tests.Integ.Logic.Products.RuleDetailTests{Method 'GetForDispensingFee'}
  =============================================
[Error] [Azos.Serialization.Slim.SlimSerializationException] Exception in SlimSerializer.Serialize():  [System.ArgumentException] An item with the same key has already been added.
   at Azos.Serialization.Slim.SlimSerializer.Serialize(Stream stream, Object root) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\SlimSerializer.cs:line 210
   at Azos.Pile.DefaultPileBase.serialize(Object payload, Int32& payloadSize, Byte& serVersion) in C:\Zdev\ghub\AZOS\src\Azos\Pile\PileImpl\DefaultPileBase.cs:line 1345
   at Azos.Pile.DefaultPileBase.put(_segment lockedSegment, Object obj, Byte[] buffer, Int32 serializedSize, Byte serializerVersion, Int32 preallocateBlockSize, Boolean isLink) in C:\Zdev\ghub\AZOS\src\Azos\Pile\PileImpl\DefaultPileBase.cs:line 520
   at Azos.Pile.DefaultPileBase.Put(Object obj, UInt32 lifeSpanSec, Int32 preallocateBlockSize) in C:\Zdev\ghub\AZOS\src\Azos\Pile\PileImpl\DefaultPileBase.cs:line 507
   at Azos.Pile.LocalCacheTable`1.<putEntry>b__36_0(Object o) in C:\Zdev\ghub\AZOS\src\Azos\Pile\LocalCacheTable.cs:line 1005
   at Azos.Pile.LocalCacheTable`1.putEntryDurable(_entry[] entries, TKey key, Int32 hashCode, Object data, PilePointer ptrData, Int32 existingAgeSec, Int32 maxAgeSec, Nullable`1 absoluteExpirationUTC, Func`2 fPilePut) in C:\Zdev\ghub\AZOS\src\Azos\Pile\LocalCacheTable.cs:line 1024
   at Azos.Pile.LocalCacheTable`1.putEntry(_bucket bucket, TKey key, Int32 hashCode, Object data, Int32 maxAgeSec, Int32 priority, Nullable`1 absoluteExpirationUTC) in C:\Zdev\ghub\AZOS\src\Azos\Pile\LocalCacheTable.cs:line 1005
   at Azos.Pile.LocalCacheTable`1.Put(TKey key, Object obj, Nullable`1 maxAgeSec, Int32 priority, Nullable`1 absoluteExpirationUTC) in C:\Zdev\ghub\AZOS\src\Azos\Pile\LocalCacheTable.cs:line 769
   at Azos.Data.CacheExtensions.<FetchThroughAsync>d__3`2.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos\Data\CacheExtensions.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Erx.Business.Areas.Products.Plan.Rules.RuleManagementLogic.<getRuleDetailsAsync>d__8.MoveNext() in C:\Repos\Business\src\Erx.Business.Logic\Areas\Products\Plan\Rules\RuleManagementLogic.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Erx.Business.Areas.Products.Plan.Rules.RuleManagementLogic.<GetRuleDetailsAsync>d__7.MoveNext() in C:\Repos\Business\src\Erx.Business.Logic\Areas\Products\Plan\Rules\RuleManagementLogic.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Erx.Business.Tests.Integ.Logic.Products.RuleDetailTests.<GetForDispensingFee>d__4.MoveNext() in C:\Repos\Business\src\testing\Erx.Business.Tests.Integ\Logic\Products\Plan\Rules\RuleDetailTests.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azos.Scripting.Runner.InvokeRunMethod(Object runnable, FID id, ValueTuple`2 method, Object[]& args) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 444
   at Azos.Scripting.Runner.SafeRunMethod(Object runnable, ValueTuple`2 method) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 376

[Error[1]] [System.ArgumentException] An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Azos.Serialization.Slim.RefPool.getIndex(Object reference, Boolean& added) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\RefPool.cs:line 260
   at Azos.Serialization.Slim.RefPool.GetHandle(Object reference, TypeRegistry treg, SlimFormat format, Type& type) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\RefPool.cs:line 140
   at Azos.Serialization.Slim.TypeSchema.writeRefMetaHandle(SlimWriter writer, TypeRegistry registry, RefPool refs, Object instance, StreamingContext streamingContext) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\TypeSchema.cs:line 606
   at lambda_method(Closure , Object )
   at Azos.Serialization.SerializationUtils.WalkArrayWrite(Array arr, Action`1 each) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\SerializationUtils.cs:line 186
   at lambda_method(Closure , TypeSchema , SlimWriter , TypeRegistry , RefPool , Object , StreamingContext )
   at Azos.Serialization.Slim.TypeDescriptor.SerializeInstance(SlimWriter writer, TypeRegistry registry, RefPool refs, Object instance, StreamingContext streamingContext) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\TypeSchema.cs:line 90
   at Azos.Serialization.Slim.TypeSchema.Serialize(SlimWriter writer, TypeRegistry registry, RefPool refs, Object instance, StreamingContext streamingContext, Type valueType) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\TypeSchema.cs:line 598
   at Azos.Serialization.Slim.SlimSerializer.serialize(SlimWriter writer, Object root, RefPool pool) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\SlimSerializer.cs:line 340
   at Azos.Serialization.Slim.SlimSerializer.Serialize(Stream stream, Object root) in C:\Zdev\ghub\AZOS\src\Azos\Serialization\Slim\SlimSerializer.cs:line 199

  Error #2 from: Erx.Business.Tests.Integ.Api.Tunnel.EpsroiTests{Method 'PostTestMemSearchWithNull'}
  =============================================
[Error] [Azos.Web.WebCallException] Web call to `..sys/datatunnel/reader` was unsuccessful: HTTP 490 - 490
   at Azos.Web.WebCallExtensions.<CallAndGetJsonMapAsync>d__6.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos\Web\WebCallExtensions.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azos.Web.WebCallExtensions.<PostAndGetJsonMapAsync>d__1.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos\Web\WebCallExtensions.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Erx.Business.Tests.Integ.Api.Tunnel.EpsroiTests.<PostTestMemSearchWithNull>d__4.MoveNext() in C:\Repos\Business\src\testing\Erx.Business.Tests.Integ\Api\Tunnel\EpsroiTests.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azos.Scripting.Runner.InvokeRunMethod(Object runnable, FID id, ValueTuple`2 method, Object[]& args) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 444
   at Azos.Scripting.Runner.SafeRunMethod(Object runnable, ValueTuple`2 method) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 376

  Error #3 from: Erx.Business.Tests.Integ.Api.Products.Plan.RuleDetailTests{Method 'GetForCopay'}
  =============================================
[Error] [System.Net.Http.HttpRequestException] Response status code does not indicate success: 500 (Internal Error).
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azos.Web.WebCallExtensions.<GetJsonMapAsync>d__0.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos\Web\WebCallExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Erx.Business.Tests.Integ.Api.Products.Plan.RuleDetailTests.<GetForCopay>d__2.MoveNext() in C:\Repos\Business\src\testing\Erx.Business.Tests.Integ\Api\Products\Plan\Rules\RuleDetailTests.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azos.Scripting.Runner.InvokeRunMethod(Object runnable, FID id, ValueTuple`2 method, Object[]& args) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 444
   at Azos.Scripting.Runner.SafeRunMethod(Object runnable, ValueTuple`2 method) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 376

  Error #4 from: Erx.Business.Tests.Integ.Api.IDP.IDPFacadeTests{Method 'CreateUserTest'}
  =============================================
[Error] [Azos.Web.WebCallException] Web call to `../user/idp` was unsuccessful: HTTP 500 - InternalServerError
   at Azos.Web.WebCallExtensions.<CallAndGetJsonMapAsync>d__6.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos\Web\WebCallExtensions.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azos.Web.WebCallExtensions.<PostAndGetJsonMapAsync>d__1.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos\Web\WebCallExtensions.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Erx.Business.Tests.Integ.Api.IDP.IDPFacadeTests.<CreateUserTest>d__1.MoveNext() in C:\Repos\Business\src\testing\Erx.Business.Tests.Integ\Api\IDP\IDPFacadeTests.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azos.Scripting.Runner.InvokeRunMethod(Object runnable, FID id, ValueTuple`2 method, Object[]& args) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 444
   at Azos.Scripting.Runner.SafeRunMethod(Object runnable, ValueTuple`2 method) in C:\Zdev\ghub\AZOS\src\Azos\Scripting\Runner.cs:line 376

   OK: 321   ERROR: 4    TOTAL: 325

**Comment by foliage71** [comment]
The problem might arise that RefPool uses Equals which is overriden for data Doc, so something is marked as a KEY on field declaration so Equals does not return true and duplicate gets enetered in ref pool, inspect refPool for usage of reference comparer? Not sure what else, but the model is like so:
```
{
  collection: [54 items]
}
```

**Comment by zhabis** [comment]
Is something screwed up with ts_cached version of RefPool? RefPool does use object ref comparison only

**Comment by foliage71** [comment]
The code that build the model:
```
protected override async Task<RowsetBase> DoPopulateRowsetFromReader(OracleCRUDQueryExecutionContext ctx, OracleDataReader reader, string target, Query query, QuerySource qSource, bool oneDoc)
    {
      var schema = Schema.GetForTypedDoc<DispensingFeeRule>();
      var store = ctx.DataStore; /* TODO: jpk can we remove context since it is unused */
      var result = new Rowset(schema);

      if (await reader.ReadAsync())
      {
        var sec = (ulong)(reader.AsLongField("BITFLAGS") ?? 0);
        var doc = new DispensingFeeRule
        {
          Name = reader.AsStringField("HANDLER"),
          Variations = new List<DispensingFeeRule.Variation> { },
          Security = (sec &
                (ulong)HandlerDispFee.SECURE_HANDLER) ==
                (ulong)HandlerDispFee.SECURE_HANDLER
        };
        result.Add(doc);
        do
        {
          var bf = (ulong)(reader.AsLongField("BITFLAGS") ?? 0);

          DispensingFeeRule.Variation rval = new DispensingFeeRule.Variation
          {
            LastUpdate = DataConversion.ConvertDateTimeFromLaker(reader.AsDateTimeField("DATECHANGED")),
            Type = reader.AsStringField("TYPE"),
            Basis = reader.AsStringField("DISPFEEBASIS"),
            Dollars = reader.AsDecimalField("DOLLARS"),
            MacIncentive = reader.AsLongField("MACINCENTIVE"),
            TierMax = reader.AsIntField("TIERMAX"),
            UseLesserFee = (bf &
                (ulong)HandlerDispFee.USE_LESSER_FEE) ==
                (ulong)HandlerDispFee.USE_LESSER_FEE
          };
          doc.Variations.Add(rval);
        }
        while (await reader.ReadAsync());
      }
      return result;
    }
```

**Comment by zhabis** [comment]
FIXED.
The issue was caused by a bad refactoring to `Collections.ReferenceEqualityComparer<object>.Instance` which defaulted to MSFT's implementation which used overriden `.Equals` on data document instead of using reference comparison. The `Collections.ReferenceEqualityComparer<T>` has been re-implemented to get rid of dubious `EqualityComparer<T>.Default` behaviour which is incorrect.
The whole design Micorosft did around `.Default` is questionable which this case clearly illustrates as it provides unknown semantics

**Comment by zhabis** [comment]
The `RefPool` in SlimSerializer was using bad implementation of ReferenceEqualityComparer.

This happened after "suggested" refactoring to use `EqualityComparer<T>` as a base class.
This was a very bad idea. NEVER USE `EqualityComparer<T>.Default`

```
  /// <summary>
  /// Checks for reference equality
  /// </summary>
  public sealed class ReferenceEqualityComparer<T> : IEqualityComparer<T>, IEqualityComparer
  {
    public static readonly ReferenceEqualityComparer<T> Instance = new ReferenceEqualityComparer<T>();

    private ReferenceEqualityComparer() {}

    public bool Equals(T x, T y) => object.ReferenceEquals(x, y);
    public int GetHashCode(T obj) => RuntimeHelpers.GetHashCode(obj);

    bool IEqualityComparer.Equals(object x, object y) => object.ReferenceEquals(x, y);
    int IEqualityComparer.GetHashCode(object obj) => RuntimeHelpers.GetHashCode(obj);
  }
```

**Comment by FAIZFREADY** [comment]
Need guide for sharing

**Comment by zhabis** [comment]
@FAIZFREADY  please provide more details, sharing of what?
