### ISSUE TITLE
API Doc bug in markdownutils

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#359]
```
2. System.ArgumentOutOfRangeException
Length cannot be less than zero. Parameter name: length
Stack:
at System.String.Substring(Int32 startIndex, Int32 length)
at Azos.Text.MarkdownUtils.<MarkdownToHtml>g__processBoldItalic|9_2(String line) in C:\Zdev\ghub\AZOS\src\Azos\Text\MarkdownUtils.cs:line 317
at Azos.Text.MarkdownUtils.<MarkdownToHtml>g__processLine|9_1(<>c__DisplayClass9_0& ) in C:\Zdev\ghub\AZOS\src\Azos\Text\MarkdownUtils.cs:line 285
at Azos.Text.MarkdownUtils.MarkdownToHtml(String content) in C:\Zdev\ghub\AZOS\src\Azos\Text\MarkdownUtils.cs:line 330
at Azos.Wave.Mvc.ApiDocController.Scope(String id) in C:\Zdev\ghub\AZOS\src\Azos.Wave\Mvc\ApiDocController.cs:line 299
```

![image](https://user-images.githubusercontent.com/46359094/96774255-bb74cd80-13b3-11eb-8365-9722ab3ed407.png)

**Comment by erxdkh** [comment]
This is caused by pattern like:
```
\*  aaa
\*\* bbbbb
```

**Comment by itadapter** [comment]
DONE
