### ISSUE TITLE
Log chronicle insert should default Message date to UTCNow as it may not always pass from scripting client

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#366]

**Comment by erxdkh** [comment]
@20201102-163428.342, b121ed2a-e776-4613-90a0-6977a7214861, ESSMIX-WP001, Critical, Instr, MongoChronicleStore@95.WriteAsync, NullReferenceException[1] First: System.NullReferenceException: Object reference not set to an instance of an object.
   at Azos.Sky.Chronicle.Server.MongoChronicleStore.<WriteAsync>b__18_0(Message msg) in C:\Zdev\ghub\AZOS\src\providers\Azos.Sky.MongoDb\Chronicle\MongoChronicleStore.cs:line 100
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Azos.Sky.Chronicle.Server.MongoChronicleStore.WriteAsync(LogBatch data) in C:\Zdev\ghub\AZOS\src\providers\Azos.Sky.MongoDb\Chronicle\MongoChronicleStore.cs:line 99

**Comment by erxdkh** [comment]
It does not check for bad data posted like:    {Data: {}}  should be  {Data: [{...},{...}]}
