### ISSUE TITLE
Suspected MongoDb Connection Corruption after command timeout

### ISSUE THREAD

**Issue by JohnPKosh** [azist/azos#442]

**Comment by itadapter** [comment]
Looks like it IS related to MongoDb connection.
The problem starts AFTER execution of a query which takes longer than defined timeout. This leaves connection in torn state.

@JohnPKosh  The problem is self-healing after a period of inactivity the torn connections get closed for good and problem goes away

**Comment by erxdkh** [comment]
Related:
```
20210303-232959.680, a3828751-c357-49a1-8f36-48e8ad06900a, ESSMIX-WP001, Critical, Instr, MongoChronicleStore@95.WriteAsync, MongoDbConnectorServerException[1] First: Azos.Data.Access.MongoDb.Connector.MongoDbConnectorServerException: Cursor not found by the server
   at Azos.Data.Access.MongoDb.Connector.Protocol.CheckReplyDataForErrors(ReplyData reply) in C:\Zdev\ghub\AZOS\src\providers\Azos.MongoDb\Connector\Protocol.cs:line 206
   at Azos.Data.Access.MongoDb.Connector.Protocol.Read_CRUD_Response(String operation, Stream stream) in C:\Zdev\ghub\AZOS\src\providers\Azos.MongoDb\Connector\Protocol.cs:line 227
   at Azos.Data.Access.MongoDb.Connector.Collection.Insert(BSONDocument[] documents) in C:\Zdev\ghub\AZOS\src\providers\Azos.MongoDb\Connector\Collection.cs:line 147
   at Azos.Sky.Chronicle.Server.MongoChronicleStore.WriteAsync(LogBatch data) in C:\Zdev\ghub\AZOS\src\providers\Azos.Sky.MongoDb\Chronicle\MongoChronicleStore.cs:line 116

```

**Comment by itadapter** [comment]
Updated connector tests
```
C:\Zdev\ghub\azos\out\Debug\run-netf>trun Azos.Tests.Integration.dll -r namespaces=*MongoDb*

Azos Test Runner
Copyright (c) 2020 Azist Group
Version 3.5 / Azos as of Dec 2019

Platform runtime: DotNetFrameworkRuntime
Runner host: TestRunnerConsoleHost
Assembly: Azos.Tests.Integration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Runner: Runner

Started 03/10/2021 19:54:46
Starting Azos.Tests.Integration::Azos.Tests.Integration.MongoDb.BasicConnectorFunctionality ...
  - AllocClient [OK]
  - CollectionLifecycle [OK]
  - InsertDelete [OK]
  - InsertWithoutID [OK]
  - CollectionDrop [OK]
  - Ping [OK]
  - Ping_Parallel Ping Parallel: 123,000 times in 808 ms at 152,228 ops/sec
[OK]
  - Insert_FindOne_Parallel  {maxConnections=0} Insert Parallel: 75,000 times in 811 ms at 92,478 ops/sec   MAX CONNECTIONS=0
FindOne Parallel: 75,000 times in 664 ms at 112,952 ops/sec   MAX CONNECTIONS=0
[OK]
  - Insert_FindOne_Parallel  {maxConnections=2} [1] Insert Parallel: 75,000 times in 3,913 ms at 19,167 ops/sec   MAX CONNECTIONS=2
FindOne Parallel: 75,000 times in 3,491 ms at 21,484 ops/sec   MAX CONNECTIONS=2
[OK]
  - Insert_Find_PrimitiveTypes [OK]
  - Insert_Find_PrimitiveTypesSingleEntry [OK]
  - Insert_Find_UnicodeStings [OK]
  - Find_Comparison_DateTime [OK]
  - Find_Comparison_Int32 [OK]
  - Update_SimpleStringInt23Entries [OK]
  - Update_Parallel_SimpleStringInt23Entries [OK]
  - Save_AsInsert [OK]
  - Save_AsInsertAndUpdate [OK]
  - Save_Parallel_AsInsertAndUpdate [OK]
  - Delete_NoLimit [OK]
  - Delete_OnlyFirstMatch [OK]
  - Delete_Parallel [OK]
... done BasicConnectorFunctionality


   OK: 22   ERROR: 0    TOTAL: 22

Starting Azos.Tests.Integration::Azos.Tests.Integration.MongoDb.CRUDwithRowConverter ...
  - T_01_Insert [OK]
  - T_01_Insert_Parallel 37,197 row inserted in 0.736 sec on 50,551 ops/sec
74,394 row red in 1.288 sec on 57,743 ops/sec
[OK]
  - T_02_Update [OK]
  - T_02_Update_Parallel 11,973 row inserted in 0.241 sec on 49,747 ops/sec
11,973 row updated in 0.293 sec on 40,870 ops/sec
35,919 row red in 0.626 sec on 57,420 ops/sec
[OK]
  - T_03_Update [OK]
  - T_04_Array [OK]
... done CRUDwithRowConverter


   OK: 28   ERROR: 0    TOTAL: 28


+------------------------------------------------
|  Platform runtime: DotNetFrameworkRuntime
|  Total runnables: 25
|  Total methods: 28
|  Finished: 03/10/2021 19:55:25
|  Running time: 00:00:38.9393542
+------------------------------------------------

   OK: 28   ERROR: 0    TOTAL: 28
```

**Comment by itadapter** [comment]
Results on .Net Core
```
C:\Zdev\ghub\azos\out\Debug\run-core>dotnet trun.dll Azos.Tests.Integration.dll -r namespaces=*MongoDb*

Azos Test Runner
Copyright (c) 2020 Azist Group
Version 3.5 / Azos as of Dec 2019

Platform runtime: NetCore20Runtime
Runner host: TestRunnerConsoleHost
Assembly: Azos.Tests.Integration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Runner: Runner

Started 03/10/2021 19:58:36
Starting Azos.Tests.Integration::Azos.Tests.Integration.MongoDb.BasicConnectorFunctionality ...
  - AllocClient [OK]
  - CollectionLifecycle [OK]
  - InsertDelete [OK]
  - InsertWithoutID [OK]
  - CollectionDrop [OK]
  - Ping [OK]
  - Ping_Parallel Ping Parallel: 123,000 times in 817 ms at 150,551 ops/sec
[OK]
  - Insert_FindOne_Parallel  {maxConnections=0} Insert Parallel: 75,000 times in 827 ms at 90,689 ops/sec   MAX CONNECTIONS=0
FindOne Parallel: 75,000 times in 677 ms at 110,783 ops/sec   MAX CONNECTIONS=0
[OK]
  - Insert_FindOne_Parallel  {maxConnections=2} [1] Insert Parallel: 75,000 times in 4,127 ms at 18,173 ops/sec   MAX CONNECTIONS=2
FindOne Parallel: 75,000 times in 3,575 ms at 20,979 ops/sec   MAX CONNECTIONS=2
[OK]
  - Insert_Find_PrimitiveTypes [OK]
  - Insert_Find_PrimitiveTypesSingleEntry [OK]
  - Insert_Find_UnicodeStings [OK]
  - Find_Comparison_DateTime [OK]
  - Find_Comparison_Int32 [OK]
  - Update_SimpleStringInt23Entries [OK]
  - Update_Parallel_SimpleStringInt23Entries [OK]
  - Save_AsInsert [OK]
  - Save_AsInsertAndUpdate [OK]
  - Save_Parallel_AsInsertAndUpdate [OK]
  - Delete_NoLimit [OK]
  - Delete_OnlyFirstMatch [OK]
  - Delete_Parallel [OK]
... done BasicConnectorFunctionality


   OK: 22   ERROR: 0    TOTAL: 22

Starting Azos.Tests.Integration::Azos.Tests.Integration.MongoDb.CRUDwithRowConverter ...
  - T_01_Insert [OK]
  - T_01_Insert_Parallel 37,197 row inserted in 0.729 sec on 51,008 ops/sec
74,394 row red in 1.304 sec on 57,048 ops/sec
[OK]
  - T_02_Update [OK]
  - T_02_Update_Parallel 11,973 row inserted in 0.242 sec on 49,407 ops/sec
11,973 row updated in 0.297 sec on 40,315 ops/sec
35,919 row red in 0.621 sec on 57,870 ops/sec
[OK]
  - T_03_Update [OK]
  - T_04_Array [OK]
... done CRUDwithRowConverter


   OK: 28   ERROR: 0    TOTAL: 28


+------------------------------------------------
|  Platform runtime: NetCore20Runtime
|  Total runnables: 25
|  Total methods: 28
|  Finished: 03/10/2021 19:59:15
|  Running time: 00:00:39.0246779
+------------------------------------------------

   OK: 28   ERROR: 0    TOTAL: 28
```
