### ISSUE TITLE
Check Authority service boot does not hang init process - should abort it

### ISSUE THREAD

**Issue by g8sun** [azist/azos#490]
```
@20210624-125537|810ce1b8-5d8d-4518-9763-533a17a38317|PC||
CatastrophicError|App|app.ini.mod|0
Error in call module root .ApplicationAfterInit()[Azos.Sky.Identification.GdidException] GdidAuthorityServiceBase locations configuration error: Location 'local-hdd-1'. Config error: Path `c:\sky\gdid` does not exist 


  +-Exception 
  | Type      Azos.Sky.Identification.GdidException
  | Source    Azos.Sky
  | Target    DoStart
  | Message   GdidAuthorityServiceBase locations configuration error: Location 'local-hdd-1'. Config error: Path `c:\sky\gdid` does not exist 
       .      
  | `SKYE-S` = ""
  | `SKYE-T` = ""
  | `AE-C` = "0"
  | Stack     
     at Azos.Sky.Identification.Server.GdidAuthorityServiceBase.DoStart() in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\Server\GdidAuthorityServiceBase.cs:line 170
     at Azos.Apps.Daemon.Start() in C:\Zdev\ghub\AZOS\src\Azos\Apps\Daemon.cs:line 167
     at Azos.Sky.Identification.Server.GdidAuthorityModule.DoApplicationAfterInit() in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\Server\GdidAuthorityModule.cs:line 57
     at Azos.Apps.ModuleBase.Azos.Apps.IModuleImplementation.ApplicationAfterInit() in C:\Zdev\ghub\AZOS\src\Azos\Apps\ModuleBase.cs:line 121
     at Azos.CollectionUtils.ForEach[T](IEnumerable`1 src, Action`1 action) in C:\Zdev\ghub\AZOS\src\Azos\CollectionUtils.cs:line 42
     at Azos.Apps.ModuleBase.Azos.Apps.IModuleImplementation.ApplicationAfterInit() in C:\Zdev\ghub\AZOS\src\Azos\Apps\ModuleBase.cs:line 124
     at Azos.Apps.CommonApplicationLogic.DoModuleAfterInitApplication() in C:\Zdev\ghub\AZOS\src\Azos\Apps\CommonApplicationLogic.Init.cs:line 145
```

**Comment by itadapter** [comment]
TBD...
