### ISSUE TITLE
Chronicle server logic ShardKEy isse for Gdid Accessor

### ISSUE THREAD

**Issue by g8sun** [azist/azos#492]
```

@20210624-141937|7ce7e00a-0917-411a-a001-4d562600c1e4|PC||35772299-a758-4d70-bf77-437cc4a7f896
CatastrophicError|Instr|ChronicleServerLogic@92.WriteAsync|193
Gdid generation failed: [Azos.CallGuardException] Guarded method '.ctor@ShardKey.cs:64' clause '<unknown>' may not be type cast to 'IDistributedStableHashProvider'

  +-Exception 
  | Type      Azos.CallGuardException
  | Source    Azos
  | Target    CastTo
  | Message   Guarded method '.ctor@ShardKey.cs:64' clause '<unknown>' may not be type cast to 'IDistributedStableHashProvider'
  | `GUARD-DETAILS` = "False"
  | `GUARD-SITE` = ".ctor@ShardKey.cs:64"
  | `GUARD-PARAM` = ""
  | `AE-C` = "0"
  | Stack     
     at Azos.GuardUtils.CastTo[TResult](Object value, String name, String callFile, Int32 callLine, String callMember) in C:\Zdev\ghub\AZOS\src\Azos\GuardUtils.cs:line 315
     at Azos.ShardKey..ctor(Object key) in C:\Zdev\ghub\AZOS\src\Azos\ShardKey.cs:line 64
     at Azos.Sky.Identification.GdidAuthorityWebAccessor.AllocateBlockAsync(String scopeName, String sequenceName, Int32 blockSize, Nullable`1 vicinity) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidAuthorityWebAccessor.cs:line 65
     at Azos.Sky.Identification.GdidGenerator.allocateBlockSomewhere(sequence seq, Int32 blockSize, Nullable`1 vicinity) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidGenerator.cs:line 579
     at Azos.Sky.Identification.GdidGenerator.allocateBlock(sequence seq, Int32 blockSize, Nullable`1 vicinity) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidGenerator.cs:line 565
     at Azos.Sky.Identification.GdidGenerator.TryGenerateManyConsecutiveGdids(String scopeName, String sequenceName, Int32 gdidCount, Nullable`1 vicinity, Boolean noLWM) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidGenerator.cs:line 516
     at Azos.Sky.Chronicle.Server.ChronicleServerLogic.WriteAsync(LogBatch data) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Chronicle\Server\ChronicleServerLogic.cs:line 146
```

**Comment by g8sun** [comment]
More details:
```
@20210624-172304|2f1400c8-2ba4-4345-a217-fa9492519a18|DEV-MIX02||e24ad924-1fa1-4a18-8173-794749915766
CatastrophicError|Instr|ChronicleServerLogic@92.WriteAsync|193
Gdid generation failed: [Azos.CallGuardException] Guarded method '.ctor@ShardKey.cs:64' clause '<unknown>' may not be type cast to 'IDistributedStableHashProvider'

  +-Exception 
  | Type      Azos.CallGuardException
  | Source    Azos
  | Target    CastTo
  | Message   Guarded method '.ctor@ShardKey.cs:64' clause '<unknown>' may not be type cast to 'IDistributedStableHashProvider'
  | `GUARD-DETAILS` = "False"
  | `GUARD-SITE` = ".ctor@ShardKey.cs:64"
  | `GUARD-PARAM` = ""
  | `AE-C` = "0"
  | Stack     
     at Azos.GuardUtils.CastTo[TResult](Object value, String name, String callFile, Int32 callLine, String callMember) in C:\Zdev\ghub\AZOS\src\Azos\GuardUtils.cs:line 315
     at Azos.ShardKey..ctor(Object key) in C:\Zdev\ghub\AZOS\src\Azos\ShardKey.cs:line 64
     at Azos.Sky.Identification.GdidAuthorityWebAccessor.<AllocateBlockAsync>d__12.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidAuthorityWebAccessor.cs:line 65
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Azos.Sky.Identification.GdidGenerator.allocateBlockSomewhere(sequence seq, Int32 blockSize, Nullable`1 vicinity) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidGenerator.cs:line 579
     at Azos.Sky.Identification.GdidGenerator.allocateBlock(sequence seq, Int32 blockSize, Nullable`1 vicinity) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidGenerator.cs:line 565
     at Azos.Sky.Identification.GdidGenerator.TryGenerateManyConsecutiveGdids(String scopeName, String sequenceName, Int32 gdidCount, Nullable`1 vicinity, Boolean noLWM) in C:\Zdev\ghub\AZOS\src\Azos.Sky\Identification\GdidGenerator.cs:line 516
     at Azos.Sky.Chronicle.Server.ChronicleServerLogic.<WriteAsync>d__20.MoveNext() in C:\Zdev\ghub\AZOS\src\Azos.Sky\Chronicle\Server\ChronicleServerLogic.cs:line 146
```

**Comment by zhabis** [comment]
The issue truly was with `ShardKey` introduction which created an ambiguous `ShardKey(object)` constructor. Refactored to only allow `IDistributedStableHashProvider`-derived objects, so the method is not able to take "any object" anymore which led to unpredictable results
