### ISSUE TITLE
Inability to return polymorphic document out of query handler? How did this work before?

### ISSUE THREAD

**Issue by g8sun** [azist/azos#550]
[Azos.Data.DataException] CRUD rowset was supplied either a null row or a row with a different schema
   at Azos.Data.RowsetBase.Check(Doc doc) in C:\Zdev\ghub\AZOS\src\Azos\Data\RowsetBase.cs:line 583
   at Azos.Data.RowsetBase.Insert(Doc doc) in C:\Zdev\ghub\AZOS\src\Azos\Data\RowsetBase.cs:line 258
   at Azos.Data.Access.MySql.MySqlCrudQueryHandler.DoPopulateRowsetAsync(MySqlCrudQueryExecutionContext context, MySqlDataReader reader, String target, Query query, QuerySource qSource, Boolean oneDoc)
   at Azos.Data.Access.MySql.MySqlCrudQueryHandler`1.DoExecuteParameterizedQueryAsync(MySqlCrudQueryExecutionContext ctx, Query query, TQueryParameters queryParameters)
   at Azos.Data.Access.MySql.MySqlCrudQueryHandler`1.ExecuteAsync(MySqlCrudQueryExecutionContext context, Query query, Boolean oneRow)
   at Azos.Data.Access.InstrumentedCrudQueryHandler`2.ProfileAsync[T](Func`1 body)
   at Azos.Data.Access.InstrumentedCrudQueryHandler`2.ExecuteAsync(ICrudQueryExecutionContext context, Query query, Boolean oneRow) in C:\Zdev\ghub\AZOS\src\Azos\Data\Access\CrudQueryHandler.cs:line 200
   at Azos.Data.Access.MySql.MySqlCrudDataStoreBase.DoLoadAsync(MySqlConnection cnn, MySqlTransaction transaction, Query[] queries, Boolean oneDoc)

**Comment by itadapter** [comment]
`RowsetBase.cs:582`, should use "Schema.IsCompatible(Schema derived)" which for dynamic docs checks 1:1 but for typed docs sees if the other Inherits from this one and returns true if it does, so the typed doc rowset may returna "base" schema

**Comment by zhabis** [comment]
I added 
```
    /// <summary>
    /// Returns true only when both schemas are the same references
    /// OR both schemas are for TypedDocs and this type is assignable from other schema's type.
    /// Example: a rowset of type TBase may be added document rows for Type TBase AND its descendants
    /// </summary>
    public bool IsCompatibleBaseFor(Schema other)
```
not sure how did we achieve this before? did we pad it with "root doc"???

**Comment by g8sun** [comment]
works
