### ISSUE TITLE
NRF in Config.ForestDatasource

### ISSUE THREAD

**Issue by g8kosh** [azist/azos#638]
@20220104-163311|0af47249-11b4-42cc-a22b-ab0a68f83625|DEV-MIX02||
Error|Conf|ForestDataSource@94.DoSignalStop|298
Error leaked: [System.NullReferenceException] Object reference not set to an instance of an object.

  +-Exception 
  | Type      System.NullReferenceException
  | Source    Azos
  | Target    <DoSignalStop>b__24_0
  | Message   Object reference not set to an instance of an object.
  | Stack     
     at Azos.Conf.Forest.Server.ForestDataSource.<DoSignalStop>b__24_0() in C:\Zdev\ghub\AZOS\src\Azos\Conf\Forest\Server\ForestDataSource.cs:line 174
     at Azos.CoreUtils.DontLeak(IApplicationComponent cmp, Action action, String errorText, String errorFrom, MessageType errorLogType) in C:\Zdev\ghub\AZOS\src\Azos\CoreUtils.cs:line 290

**Comment by zhabis** [comment]
was fixed long ago
