### ISSUE TITLE
Add more unit test cases for HourList, especially around NOON/MIDNIGHT time frames

### ISSUE THREAD

**Issue by itadapter** [azist/azos#713]
We need more unit tests for edge cases like John found:  "9am-12pm; 12:30pm-6pm"
Anything that happens in the 12pm hour window (at noon) is problematic

**Comment by itadapter** [comment]
```
  Dumping the first 1 errors:

  Error #1 from: Azos.Tests.Nub.Time.HourListTests{Method 'TwelvePM'}
  =============================================
[Error] [Azos.AvermentException] AreEqual((Int32)60, (Int32)780)
   at Azos.Aver.Fail(String message, String from) in C:\Zdev\ghub\azos\src\Azos\Aver.cs:line 150
   at Azos.Aver.AreEqual[T](T expect, T got, String from) in C:\Zdev\ghub\azos\src\Azos\Aver.cs:line 209
   at Azos.Tests.Nub.Time.HourListTests.TwelvePM() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\Time\HourListTests.cs:line 194


   OK: 1498   ERROR: 1    TOTAL: 1499
```
