### ISSUE TITLE
Error on TOY exit

### ISSUE THREAD

**Issue by itadapter** [azist/azos#735]
```
Strike <ENTER> to exit app

Shutting app container...
...app container is disposed
Info: Runtime: 00:00:52.0556395
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Azos.Log.Message.InitDefaultFields(IApplication app) in C:\Zdev\ghub\azos-net6\src\Azos\Log\Message.cs:line 42
   at Azos.Apps.ApplicationComponent.WriteLog(MessageType type, String from, String text, Exception error, Nullable`1 related, String pars, String file, Int32 src) in C:\Zdev\ghub\azos-net6\src\Azos\Apps\ApplicationComponent.cs:line 327
   at Azos.Pile.LocalCache.threadSpin() in C:\Zdev\ghub\azos-net6\src\Azos\Pile\LocalCache.cs:line 615
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

C:\Zdev\ghub\azos-net6\out\Debug>
```

**Comment by itadapter** [comment]
Can not reproduce...
