### ISSUE TITLE
Unit test errors in Nub

### ISSUE THREAD

**Issue by zhabis** [azist/azos#745]
Error #1 from: Azos.Tests.Nub.TaskUtilsTests{Method 'TryGetCompletedTaskResultAsObject_0'}
  =============================================
[Error] [Azos.AvermentException] IsFalse((Boolean)True)
   at Azos.Aver.Fail(String message, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 150
   at Azos.Aver.IsFalse(Boolean condition, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 273
   at Azos.Tests.Nub.TaskUtilsTests.TryGetCompletedTaskResultAsObject_0() in C:\Zdev\ghub\azos-net6\src\testing\Azos.Tests.Nub\TaskUtilsTests.cs:line 23

**Comment by zhabis** [comment]
```

  Error #1 from: Azos.Tests.Nub.Configuration.ScriptingTests{Method 'LoopWithRealArithmetic'}
  =============================================
[Error] [Azos.AvermentException] AreEqual((string)"section_0.6" of 11 chars, (string)"section_0.6000000000000001" of 26 chars, StringComparison.InvariantCulture)
   at Azos.Aver.Fail(String message, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 150
   at Azos.Aver.AreEqual(String expect, String got, StringComparison comparison, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 195
   at Azos.Aver.AreEqual(String expect, String got, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 190
   at Azos.Tests.Nub.Configuration.ScriptingTests.LoopWithRealArithmetic() in C:\Zdev\ghub\azos-net6\src\testing\Azos.Tests.Nub\Configuration\ScriptingTests.cs:line 453

  Error #2 from: Azos.Tests.Nub.BaseCollections.LookAheadEnumerableTest{Method 'EmptyEnumerable'}
  =============================================
[Error] [Azos.AvermentException] Throws<(string)"System.InvalidOperationException" of 32 chars>
   at Azos.Aver.Fail(String message, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 150
   at Azos.Aver.Throws[TException](Action action, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 334
   at Azos.Tests.Nub.BaseCollections.LookAheadEnumerableTest.EmptyEnumerable() in C:\Zdev\ghub\azos-net6\src\testing\Azos.Tests.Nub\BaseCollections\LookAheadEnumerableTest.cs:line 26

  Error #3 from: Azos.Tests.Nub.BaseCollections.LookAheadEnumerableTest{Method 'SingleEnumerable'}
  =============================================
[Error] [Azos.AvermentException] Throws<(string)"System.InvalidOperationException" of 32 chars>
   at Azos.Aver.Fail(String message, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 150
   at Azos.Aver.Throws[TException](Action action, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 334
   at Azos.Tests.Nub.BaseCollections.LookAheadEnumerableTest.SingleEnumerable() in C:\Zdev\ghub\azos-net6\src\testing\Azos.Tests.Nub\BaseCollections\LookAheadEnumerableTest.cs:line 38

  Error #4 from: Azos.Tests.Nub.BaseCollections.LookAheadEnumerableTest{Method 'MulripleEnumerable'}
  =============================================
[Error] [Azos.AvermentException] Throws<(string)"System.InvalidOperationException" of 32 chars>
   at Azos.Aver.Fail(String message, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 150
   at Azos.Aver.Throws[TException](Action action, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 334
   at Azos.Tests.Nub.BaseCollections.LookAheadEnumerableTest.MulripleEnumerable() in C:\Zdev\ghub\azos-net6\src\testing\Azos.Tests.Nub\BaseCollections\LookAheadEnumerableTest.cs:line 66
```

**Comment by zhabis** [comment]
Microsoft changed `IEnumerable.Current` does not throw `InvalidOperationException` anymore.

**Comment by zhabis** [comment]
```
 Error #1 from: Azos.Tests.Nub.Configuration.ScriptingTests{Method 'LoopWithRealArithmetic'}
  =============================================
[Error] [Azos.AvermentException] AreEqual((string)"section_0.6" of 11 chars, (string)"section_0.6000000000000001" of 26 chars, StringComparison.InvariantCulture)
   at Azos.Aver.Fail(String message, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 150
   at Azos.Aver.AreEqual(String expect, String got, StringComparison comparison, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 195
   at Azos.Aver.AreEqual(String expect, String got, String from) in C:\Zdev\ghub\azos-net6\src\Azos\Aver.cs:line 190
   at Azos.Tests.Nub.Configuration.ScriptingTests.LoopWithRealArithmetic() in C:\Zdev\ghub\azos-net6\src\testing\Azos.Tests.Nub\Configuration\ScriptingTests.cs:line 453
```

**Comment by zhabis** [comment]
DONE
![image](https://user-images.githubusercontent.com/39680879/184696313-6514760b-af39-48fd-a538-3f6fdfd0ae28.png)
