### ISSUE TITLE
NRE in Azos WebConsole (all apps):

### ISSUE THREAD

**Issue by itadapter** [azist/azos#776]
E.g. 
given ' http://octodu22.mshome.net:8100/system/webconsole'
we get

```
1. Azos.Wave.MvcActionException
Controller action body: 'Azos.Apps.Terminal.Web.WebConsole'.'index'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.
Stack:
at Azos.Wave.Handlers.MvcHandler.DoError(WorkContext work, Exception error)
at Azos.Wave.Handlers.TypeLookupHandler`1.DoHandleWorkAsync(WorkContext work)
at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)
at Azos.Wave.WorkHandler.FilterAndHandleWorkAsync(WorkContext work)
at Azos.Wave.CompositeWorkHandler.DoHandleWorkAsync(WorkContext work)
at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)
at Azos.Wave.WorkHandler.FilterAndHandleWorkAsync(WorkContext work)
at Azos.Wave.CompositeWorkHandler.DoHandleWorkAsync(WorkContext work)
at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)
at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)
at G8.Server.Web.G8CorsFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain) in C:\Zdev\ghub\g8\src\G8.Server\Web\G8CorsFilter.cs:line 101
at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)
2. System.NullReferenceException
Object reference not set to an instance of an object.
Stack:
at Azos.Apps.Terminal.Web.WebConsole.Index()
at Azos.Wave.Handlers.MvcHandler.DoTargetWorkAsync(Controller target, WorkContext work)
at Azos.Wave.Handlers.MvcHandler.DoTargetWorkAsync(Controller target, WorkContext work)
```

**Comment by itadapter** [comment]
The log chronicle has that issue too.
The problem is with template rendering as both web console and chronicle load that

**Comment by itadapter** [comment]
```json

{
  "OK": false, 
  "error": "MvcActionException", 
  "isauth": false, 
  "data": 
    {
      "ns": "wave.mvc", 
      "type": "MvcActionException", 
      "code": 0, 
      "controller": "Azos.Sky.Chronicle.Server.Web.Log", 
      "action": "view"
    }, 
  "dev::dump": 
    {
      "TypeName": "Azos.Wave.FilterPipelineException", 
      "Message": ":>realip>callflow>Portal>session>dconv>latency>cors> [Azos.Wave.MvcActionException] Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
      "Code": 0, 
      "Source": "Azos.Wave", 
      "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.ErrorFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)", 
      "AppId": "memoir", 
      "AppName": "memoir", 
      "ExternalStatus": null, 
      "InnerException": 
        {
          "TypeName": "Azos.Wave.FilterPipelineException", 
          "Message": ":>callflow>Portal>session>dconv>latency>cors> [Azos.Wave.MvcActionException] Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
          "Code": 0, 
          "Source": "Azos.Wave", 
          "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.EffectiveCallerIPEndPointFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
          "AppId": "memoir", 
          "AppName": "memoir", 
          "ExternalStatus": null, 
          "InnerException": 
            {
              "TypeName": "Azos.Wave.FilterPipelineException", 
              "Message": ":>Portal>session>dconv>latency>cors> [Azos.Wave.MvcActionException] Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
              "Code": 0, 
              "Source": "Azos.Wave", 
              "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.DistributedCallFlowFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
              "AppId": "memoir", 
              "AppName": "memoir", 
              "ExternalStatus": null, 
              "InnerException": 
                {
                  "TypeName": "Azos.Wave.FilterPipelineException", 
                  "Message": ":>session>dconv>latency>cors> [Azos.Wave.MvcActionException] Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
                  "Code": 0, 
                  "Source": "Azos.Wave", 
                  "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.PortalFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
                  "AppId": "memoir", 
                  "AppName": "memoir", 
                  "ExternalStatus": null, 
                  "InnerException": 
                    {
                      "TypeName": "Azos.Wave.FilterPipelineException", 
                      "Message": ":>dconv>latency>cors> [Azos.Wave.MvcActionException] Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
                      "Code": 0, 
                      "Source": "Azos.Wave", 
                      "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.SessionFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
                      "AppId": "memoir", 
                      "AppName": "memoir", 
                      "ExternalStatus": null, 
                      "InnerException": 
                        {
                          "TypeName": "Azos.Wave.FilterPipelineException", 
                          "Message": ":>latency>cors> [Azos.Wave.MvcActionException] Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
                          "Code": 0, 
                          "Source": "Azos.Wave", 
                          "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at G8.Server.Web.DataConversionFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain) in C:\\Zdev\\ghub\\g8\\src\\G8.Server\\Web\\DataConversionFilter.cs:line 67\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
                          "AppId": "memoir", 
                          "AppName": "memoir", 
                          "ExternalStatus": null, 
                          "InnerException": 
                            {
                              "TypeName": "Azos.Wave.FilterPipelineException", 
                              "Message": ":>cors> [Azos.Wave.MvcActionException] Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
                              "Code": 0, 
                              "Source": "Azos.Wave", 
                              "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.LatencyInstrumentationFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
                              "AppId": "memoir", 
                              "AppName": "memoir", 
                              "ExternalStatus": null, 
                              "InnerException": 
                                {
                                  "TypeName": "Azos.Wave.MvcActionException", 
                                  "Message": "Controller action body: 'Azos.Sky.Chronicle.Server.Web.Log'.'view'. Exception: [System.NullReferenceException] Object reference not set to an instance of an object.", 
                                  "Code": 0, 
                                  "Source": "Azos.Wave", 
                                  "StackTrace": "   at Azos.Wave.Handlers.MvcHandler.DoError(WorkContext work, Exception error)\n   at Azos.Wave.Handlers.TypeLookupHandler`1.DoHandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.FilterAndHandleWorkAsync(WorkContext work)\n   at Azos.Wave.CompositeWorkHandler.DoHandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.FilterAndHandleWorkAsync(WorkContext work)\n   at Azos.Wave.CompositeWorkHandler.DoHandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at G8.Server.Web.G8CorsFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain) in C:\\Zdev\\ghub\\g8\\src\\G8.Server\\Web\\G8CorsFilter.cs:line 101\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
                                  "AppId": "memoir", 
                                  "AppName": "memoir", 
                                  "ExternalStatus": null, 
                                  "InnerException": 
                                    {
                                      "TypeName": "System.NullReferenceException", 
                                      "Message": "Object reference not set to an instance of an object.", 
                                      "Code": 0, 
                                      "Source": "Azos.Sky.Server", 
                                      "StackTrace": "   at Azos.Sky.Chronicle.Server.Web.Log.View(Nullable`1 id, Nullable`1 rel)\n   at Azos.Wave.Handlers.MvcHandler.DoTargetWorkAsync(Controller target, WorkContext work)\n   at Azos.Wave.Handlers.MvcHandler.DoTargetWorkAsync(Controller target, WorkContext work)", 
                                      "AppId": "memoir", 
                                      "AppName": "memoir", 
                                      "ExternalStatus": null, 
                                      "InnerException": null
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
