### ISSUE TITLE
Bug - Chronicle archive dimensions builder fails with enabled type hints EntityId/Atom 

### ISSUE THREAD

**Issue by itadapter** [azist/azos#872]
We enabled type hints on archive dims, so now when chronicle server tries to build a n index - it fails on EntityId as it does not know how to handle types
See this:
```
@20230530-155314.852, dfbf05cd-5781-48a5-9311-a1fa0df92bb6, dsys-app-01, Critical, Instr, MongoChronicleStore@78.WriteAsync, BSONException[1] First: Azos.Serialization.BSON.BSONException: BSONDocument.Add(not supported object type 'EntityId')
   at Azos.Serialization.BSON.BSONExtensions.Add(BSONDocument document, String name, Object value, Boolean skipNull, Boolean required)
   at Azos.Serialization.BSON.BSONExtensions.ToBson(JsonDataMap map)
   at Azos.Sky.Chronicle.Server.BsonConvert.ToBson(Message msg)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Azos.Sky.Chronicle.Server.MongoChronicleStore.WriteAsync(LogBatch data)
```

**Comment by itadapter** [comment]
Is it in `Azos.Serialization.BSON.BSONExtensions.ToBson(JsonDataMap map)`?

**Comment by itadapter** [comment]
Also there is an issue with reading AD - "premature JSOn eof" see issue: 
- https://github.com/mygreatday/g8/issues/807

**Comment by itadapter** [comment]
Fixed. It was

- IEnumerable defferred processing which concelaed the error
- The erro was graph too deep when trying to fetch ad doc from mongo as it contained one more doc level for numberLong
