### ISSUE TITLE
Catastrophic failure un-binding of AzosApp/ExecContext does not unbind s_Application. URGENT!!!

### ISSUE THREAD

**Issue by itadapter** [azist/azos#876]
This must be fixed ASAP.

Folio is needs to allocate app chassis, and deallocate, but deallocation leaves s_Application instance and that prevents Folio (or others) from using this in any meaningful manner,

Must review the disappearance of unit tests in `StopAndShutdownTests` - where did other 6+ tests go?

**Comment by itadapter** [comment]
```
Started 06/08/2023 18:06:51
Starting Azos.Tests.Nub::Azos.Tests.Nub.Application.StopAndShutdownTests ...
  - Test01 [Error] [System.Exception] Apples on toaster in October: AzosApplication
   at Azos.Apps.ExecutionContext.__UnbindApplication(IApplication application) in C:\Zdev\ghub\azos\src\Azos\Apps\ExecutionContext.cs:line 139
   at Azos.Apps.CommonApplicationLogic.CleanupApplication() in C:\Zdev\ghub\azos\src\Azos\Apps\CommonApplicationLogic.Cleanup.cs:line 47
   at Azos.Apps.AzosApplication.Destructor() in C:\Zdev\ghub\azos\src\Azos\Apps\AzosApplication.cs:line 51
   at Azos.DisposableObject.Dispose() in C:\Zdev\ghub\azos\src\Azos\DisposableObject.cs:line 241
   at Azos.Tests.Nub.Application.StopAndShutdownTests.Test01() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\Application\StopAndShutdownTests.cs:line 36


... done StopAndShutdownTests


   OK: 0   ERROR: 1    TOTAL: 1
```
