### ISSUE TITLE
Bixon serializer does not properly roundtrip NLSMap values

### ISSUE THREAD

**Issue by JohnPKosh** [azist/azos#921]
See test error:

```
{
  "__bix": "$uid:bf3e4485-07b9-4797-9de6-2af4aaed93fb",
  "String1": "Mark Twain",
  "Int1": 123,
  "NInt1": 678,
  "Atom1": "$atm:#0",
  "Gdid1": "$gdi:0:0:0",
  "Jdm1": null,
  "Jar1": null,
  "Nls1":
    {
      "eng":
        {
          "n": "yes",
          "d": "confirmation"
        }
    },
  "Nls2": null,
  "Obj1": null,
  "ObjArr1": null
}

{
  "__bix": "$uid:bf3e4485-07b9-4797-9de6-2af4aaed93fb",
  "String1": "Mark Twain",
  "Int1": 123,
  "NInt1": 678,
  "Atom1": "$atm:#0",
  "Gdid1": "$gdi:0:0:0",
  "Jdm1": null,
  "Jar1": null,
  "Nls1": {},
  "Nls2": null,
  "Obj1": null,
  "ObjArr1": null,
  "Nls1_": [
      {
        "key": "eng",
        "value":
          {
            "n": "yes",
            "d": "confirmation"
          }
      }]
}
[Error] [Azos.AvermentException] AreEqual((string)"yes" of 3 chars, <null>, StringComparison.InvariantCulture)
   at Azos.Aver.Fail(String message, String from) in D:\devhome\ghub\azos\src\Azos\Aver.cs:line 150
   at Azos.Aver.AreEqual(String expect, String got, StringComparison comparison, String from) in D:\devhome\ghub\azos\src\Azos\Aver.cs:line 195
   at Azos.Aver.AreEqual(String expect, String got, String from) in D:\devhome\ghub\azos\src\Azos\Aver.cs:line 190
   at Azos.Tests.Nub.Serialization.BixonTests.RootDocWithNlsMap_01() in D:\devhome\ghub\azos\src\testing\Azos.Tests.Nub\Serialization\bix\BixonTests.cs:line 1162

```

**Comment by itadapter** [comment]
We cross checked today. All Good!
