### ISSUE TITLE
Slim Serialization issue in cache server - `EntityId?` property is a suspect

### ISSUE THREAD

**Issue by JohnPKosh** [azist/azos#924]
```
at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)\n   
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)\n   
   at lambda_method452(Closure , TypeSchema , SlimReader , TypeRegistry , RefPool , Object& , StreamingContext )\n   
   at Azos.Serialization.Slim.TypeDescriptor.DeserializeInstance(SlimReader reader, TypeRegistry registry, RefPool refs, Object& instance, StreamingContext streamingContext)\n   
   at Azos.Serialization.Slim.TypeSchema.DeserializeRootOrInner(SlimReader reader, TypeRegistry registry, RefPool refs, StreamingContext streamingContext, Boolean root, Type valueType)\n   
   at lambda_method450(Closure , TypeSchema , SlimReader , TypeRegistry , RefPool , Object& , StreamingContext )\n   
   at Azos.Serialization.Slim.TypeDescriptor.DeserializeInstance(SlimReader reader, TypeRegistry registry, RefPool refs, Object& instance, StreamingContext streamingContext)\n   
   at Azos.Serialization.Slim.TypeSchema.DeserializeRootOrInner(SlimReader reader, TypeRegistry registry, RefPool refs, StreamingContext streamingContext, Boolean root, Type valueType)\n   
   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool)\n   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream)
```

**Comment by itadapter** [comment]
This happens on 1+ fetch, when it reads it back from cache.
Looks like the modern runtime f-up the `EntityId`, maybe need to add it to `Slim`

**Comment by JohnPKosh** [comment]
```

{
  "OK": false, 
  "error": "MvcActionException", 
  "isauth": false, 
  "data": 
    {
      "ns": "wave.mvc", 
      "type": "MvcActionException", 
      "controller": "G8.As.Hub.Server.Web.Tryme", 
      "action": "svcarea"
    }, 
  "dev::dump": 
    {
      "TypeName": "Azos.Wave.FilterPipelineException", 
      "Message": ">>error>backend-info>realip>callflow>Portal>session>dconv>latency>cors>  [Azos.Wave.MvcActionException] Controller action body: 'G8.As.Hub.Server.Web.Tryme'.'svcarea'. Exception: [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [System.NotSupportedException] Specified method is not supported.", 
      "Code": 0, 
      "Source": "Azos.Wave", 
      "StackTrace": "   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.LatencyInstrumentationFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at G8.Server.Web.DataConversionFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain) in C:\\Zdev\\ghub\\g8\\src\\G8.Server\\Web\\DataConversionFilter.cs:line 67\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.SessionFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.PortalFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.DistributedCallFlowFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.EffectiveCallerIPEndPointFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at G8.Server.Web.G8BackendInfoFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain) in C:\\Zdev\\ghub\\g8\\src\\G8.Server\\Web\\G8BackendInfoFilter.cs:line 28\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at Azos.Wave.Filters.ErrorFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain)", 
      "AppId": "hub", 
      "AppName": "hub", 
      "ExternalStatus": null, 
      "InnerException": 
        {
          "TypeName": "Azos.Wave.MvcActionException", 
          "Message": "Controller action body: 'G8.As.Hub.Server.Web.Tryme'.'svcarea'. Exception: [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [System.NotSupportedException] Specified method is not supported.", 
          "Code": 0, 
          "Source": "Azos.Wave", 
          "StackTrace": "   at Azos.Wave.Handlers.MvcHandler.DoError(WorkContext work, Exception error)\n   at Azos.Wave.Handlers.TypeLookupHandler`1.DoHandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.FilterAndHandleWorkAsync(WorkContext work)\n   at Azos.Wave.CompositeWorkHandler.DoHandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.FilterAndHandleWorkAsync(WorkContext work)\n   at Azos.Wave.CompositeWorkHandler.DoHandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkHandler.HandleWorkAsync(WorkContext work)\n   at Azos.Wave.WorkFilter.InvokeNextWorkerAsync(WorkContext work, CallChain callChain)\n   at G8.Server.Web.G8CorsFilter.DoFilterWorkAsync(WorkContext work, CallChain callChain) in C:\\Zdev\\ghub\\g8\\src\\G8.Server\\Web\\G8CorsFilter.cs:line 101\n   at Azos.Wave.WorkFilter.FilterWorkAsync(WorkContext work, CallChain callChain)", 
          "AppId": "hub", 
          "AppName": "hub", 
          "ExternalStatus": null, 
          "InnerException": 
            {
              "TypeName": "Azos.Serialization.Slim.SlimDeserializationException", 
              "Message": "Exception in SlimSerializer.Deserialize():  [System.NotSupportedException] Specified method is not supported.", 
              "Code": 0, 
              "Source": "Azos", 
              "StackTrace": "   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream)\n   at Azos.Pile.DefaultPileBase.deserialize(Memory data, Int32 addr, Int32 payloadSize, Byte serVersion)\n   at Azos.Pile.DefaultPileBase.get(PilePointer ptr, Boolean raw, Byte& serVersion)\n   at Azos.Pile.DefaultPileBase.Get(PilePointer ptr)\n   at Azos.Pile.LocalCacheTable`1.Get(TKey key, Int32 ageSec)\n   at Azos.Data.CacheExtensions.FetchThroughAsync[TKey,TResult](ICache cache, TKey key, String tblCache, ICacheParams caching, Func`2 fFetch, Func`3 fFilter, Action`4 extraPut)\n   at G8.SysData.Server.AdlibPostalServiceAreaFinder.GetServiceAreaByPostalCodeAsync(String postalCode, Nullable`1 asOfUtc, ICacheParams cache) in C:\\Zdev\\ghub\\g8\\src\\G8.Base.Server\\SysData\\AdlibPostalServiceAreaFinder.cs:line 55\n   at G8.SysData.Server.SysDataLogic.GetServiceAreaByPostalCodeAsync(String postalCode, Nullable`1 asOfUtc, ICacheParams cache) in C:\\Zdev\\ghub\\g8\\src\\G8.Base.Server\\SysData\\SysDataLogic.cs:line 159\n   at G8.As.Hub.Server.Web.Tryme.GetServiceArea(String postal, Nullable`1 asof) in C:\\Zdev\\ghub\\g8\\src\\as\\G8.As.Hub.Server\\Web\\Tryme.cs:line 40\n   at Azos.Wave.Handlers.MvcHandler.DoTargetWorkAsync(Controller target, WorkContext work)\n   at Azos.Wave.Handlers.MvcHandler.DoTargetWorkAsync(Controller target, WorkContext work)", 
              "AppId": "hub", 
              "AppName": "hub", 
              "ExternalStatus": null, 
              "InnerException": 
                {
                  "TypeName": "System.NotSupportedException", 
                  "Message": "Specified method is not supported.", 
                  "Code": 0, 
                  "Source": "System.Private.CoreLib", 
                  "StackTrace": "   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)\n   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)\n   at lambda_method452(Closure , TypeSchema , SlimReader , TypeRegistry , RefPool , Object& , StreamingContext )\n   at Azos.Serialization.Slim.TypeDescriptor.DeserializeInstance(SlimReader reader, TypeRegistry registry, RefPool refs, Object& instance, StreamingContext streamingContext)\n   at Azos.Serialization.Slim.TypeSchema.DeserializeRootOrInner(SlimReader reader, TypeRegistry registry, RefPool refs, StreamingContext streamingContext, Boolean root, Type valueType)\n   at lambda_method450(Closure , TypeSchema , SlimReader , TypeRegistry , RefPool , Object& , StreamingContext )\n   at Azos.Serialization.Slim.TypeDescriptor.DeserializeInstance(SlimReader reader, TypeRegistry registry, RefPool refs, Object& instance, StreamingContext streamingContext)\n   at Azos.Serialization.Slim.TypeSchema.DeserializeRootOrInner(SlimReader reader, TypeRegistry registry, RefPool refs, StreamingContext streamingContext, Boolean root, Type valueType)\n   at Azos.Serialization.Slim.SlimSerializer.deserialize(SlimReader reader, RefPool pool)\n   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream)", 
                  "AppId": "hub", 
                  "AppName": "hub", 
                  "ExternalStatus": null, 
                  "InnerException": null, 
                  "CallFlow": null
                }, 
              "CallFlow": null
            }, 
          "CallFlow": null
        }, 
      "CallFlow": 
        {
          "tp": "wave.wc", 
          "ID": "3f278d6b-638d-44dd-8edd-63b5351cf396", 
          "DirectorName": null, 
          "CallerAddress": "184.56.32.13:0", 
          "CallerAgent": "vscode-restclient", 
          "CallerPort": "GET  \/tryme\/svcarea?postal=usa:89180", 
          "Items": []
        }
    }
}
```

**Comment by itadapter** [comment]
Look in `.....azos\src\Azos\IO` notice that the format does not support `Atom`, `Atom?`, `EntityId`, `EntityId?`

**Comment by itadapter** [comment]
Attempt to **DESER** class with `EntityId` field fails
```
[Error] [Azos.Serialization.Slim.SlimDeserializationException] Exception in SlimSerializer.Deserialize():  [System.NotSupportedException] Specified method is not supported.
   at Azos.Serialization.Slim.SlimSerializer.Deserialize(Stream stream) in C:\Zdev\ghub\azos\src\Azos\Serialization\Slim\SlimSerializer.cs:line 254
   at Azos.Tests.Nub.Serialization.Slim6Tests.Simple001() in C:\Zdev\ghub\azos\src\testing\Azos.Tests.Nub\Serialization\slim\Slim6Tests.cs:line 33
```

**Comment by itadapter** [comment]
The error in caching is gone. We re-tested all API calls - all work fine now.
